server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
        - id: hero-game-service
          uri: http://192.168.20.72:8080
          predicates:
            - Path=/game/**

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE